spring:
  cloud:
    stream:
      function:
        definition: processPayment

      bindings:
        processPayment-in-0:
          destination: order-event
        processPayment-out-0:
          destination: payment-event

server:
  port: 8082
